name: ClaudeCompass
options:
  bundleIdPrefix: com.claudecompass
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    SWIFT_VERSION: "6.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_ENTITLEMENTS: "ClaudeCompass/ClaudeCompass.entitlements"
    INFOPLIST_FILE: "ClaudeCompass/Info.plist"
    GENERATE_INFOPLIST_FILE: NO
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  ClaudeCompass:
    type: application
    platform: macOS
    sources:
      - path: ClaudeCompass
        excludes:
          - "Info.plist"
          - "ClaudeCompass.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.claudecompass.app
        INFOPLIST_KEY_CFBundleDisplayName: "Claude Compass"
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        ENABLE_APP_SANDBOX: NO
        PROVISIONING_PROFILE_SPECIFIER: ""
        CODE_SIGNING_ALLOWED: YES
        CODE_SIGNING_REQUIRED: NO
